import { Box, useColorMode, VStack, StackDivider } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Banner } from "./components/Banner";
import { TodoList } from "./components/TodoList";
import { AddTodo } from "./components/AddTodo";
import { Item } from "./types/item";
import { useState } from "react";
import Footer from "./components/Footer";
import Filtros from "./components/Filtros";

const Home: NextPage = () => {
  const { colorMode, toggleColorMode } = useColorMode();

  const [list, setList] = useState<Item[]>([]);

  const handleAddTodo = (todoItem: string) => {
    let newTodo = [...list];
    newTodo.push({
      id: list.length + 1,
      text: todoItem,
      status: false,
    });
    setList(newTodo);
  };
  return (
    <div>
      <Head>
        <title>Todo app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        {colorMode === "light" ? (
          <Banner bg={["bg-mobile-light.jpg", "bg-desktop-light.jpg"]} />
        ) : (
          <Banner bg={["bg-mobile-dark.jpg", "bg-desktop-dark.jpg"]} />
        )}
        <Box>
          {colorMode === "light" ? (
            <VStack>
              <AddTodo onEnter={handleAddTodo} />
              <VStack
                align="stretch"
                divider={<StackDivider borderColor="gray.100" />}
                borderRadius="sm"
                w="50%"
                bg={"#fafafa"}
              >
                {list.map((item, index) => (
                  <TodoList key={index} item={item} />
                ))}
                <Filtros />
              </VStack>
              <Footer />
            </VStack>
          ) : (
            <VStack>
              <AddTodo onEnter={handleAddTodo} />
              <VStack
                align="stretch"
                divider={<StackDivider borderColor="#4d5066" />}
                borderRadius="sm"
                w="50%"
                bg={"#25273c"}
              >
                {list.map((item, index) => (
                  <TodoList key={index} item={item} />
                ))}
                <Filtros />
              </VStack>
              <Footer />
            </VStack>
          )}
        </Box>
      </main>
    </div>
  );
};
export default Home;
